name: Jenkins CI Pipeline Trigger

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  trigger-jenkins-pipeline:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Download Jenkins WAR (if needed for local Jenkins setup)
      - name: Download Jenkins WAR
        run: |
          mkdir -p ${{ runner.temp }}/jenkins
          curl -L -o ${{ runner.temp }}/jenkins/jenkins.war https://get.jenkins.io/war-stable/latest/jenkins.war

      # Step 3: Trigger Jenkins pipeline
      - name: Trigger Jenkins Pipeline
        uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt