# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Suite - Manual Trigger - Run all tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn clean test

    - name: Upload reports artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: src/test/reports

    - name: Add summary
      if: always()
      run: |
        echo "### 🧪 Test Results Summary" >> $GITHUB_STEP_SUMMARY
        total=$(grep -ho 'Tests run: [0-9]*' target/surefire-reports/*.txt | awk '{s+=$3} END {print s}')
        failed=$(grep -ho 'Failures: [0-9]*' target/surefire-reports/*.txt | awk '{s+=$2} END {print s}')
        skipped=$(grep -ho 'Skipped: [0-9]*' target/surefire-reports/*.txt | awk '{s+=$2} END {print s}')
        passed=$((total - failed - skipped))
        echo "- Total Tests: $total" >> $GITHUB_STEP_SUMMARY
        echo "- Passed: $passed" >> $GITHUB_STEP_SUMMARY
        echo "- Failures: $failed" >> $GITHUB_STEP_SUMMARY
        echo "- Skipped: $skipped" >> $GITHUB_STEP_SUMMARY
        
    - name: Send email with execution report
      uses: dawidd6/action-send-mail@v5
      if: always() # This ensures the email is sent even if previous steps fail
      with:
        # SMTP connection details
        server_address: smtp.gmail.com # Or your SMTP server
        server_port: 465 # Or your SMTP port (e.g., 587 for TLS/STARTTLS)
        secure: true # Use 'true' for SSL/TLS, 'false' for plain (or 'starttls' for STARTTLS)

        # Authentication credentials from GitHub Secrets
        username: pottersavenue@gmail.com
        password: Passport.273

        # Email details
        subject: "CI/CD Execution Report - ${{ github.workflow }} - ${{ github.ref_name }} branch"
        to: "sagar.k161@gmail.com" # Comma-separated list of recipients
        from: "CI/CD Automation <${{ secrets.MAIL_USERNAME }}>" # Optional: customize sender name

        # Email body (can be plain text, HTML, or Markdown)
        html_body: file://src/test/reports/TestReport_.html # Path to your HTML report
        # Or for a simple text body:
        # body: |
        #   CI/CD workflow run for ${{ github.repository }} on branch ${{ github.ref_name }}.
        #   Status: ${{ job.status }}
        #   See attached report for details.
        #   Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        # Attachments
        attachments: src/test/reports/TestReport_.html